<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ59iuae\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ59iuae/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJ59iuae.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJ59iuae\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJ59iuae\appDevDebugProjectContainer([
    'container.build_hash' => 'J59iuae',
    'container.build_id' => 'a5092b43',
    'container.build_time' => 1565637700,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ59iuae');
